<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => 'Dashboard',
                'url' => '',
                'icon_type' => 0,
                'icon_image' => 'fa-home',
                'is_parent' => 0,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'Add Leave Record',
                'url' => 'add-leaves',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Users',
                'url' => '#',
                'icon_type' => 0,
                'icon_image' => 'fa-users',
                'is_parent' => 0,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Delete Leave Type',
                'url' => 'delete-leavetype/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'Edit Leave Type',
                'url' => 'edit-leavetype/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'Add Leave Type',
                'url' => 'add-leavestype',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'Leaves Record',
                'url' => 'list-leaves-record',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 4,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Leave Type',
                'url' => 'list-leaves-type',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 3,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'Employees Document',
                'url' => 'add-employees-document',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 2,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Employees List',
                'url' => 'list-employees',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 1,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'HR',
                'url' => '#',
                'icon_type' => 0,
                'icon_image' => 'fa-briefcase',
                'is_parent' => 0,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Logs',
                'url' => 'logs-list',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 5,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'View Roles',
                'url' => 'view-roles',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 4,
                'is_enabled' => 1,
                'is_new_tab' => 1,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Add Roles',
                'url' => 'add-roles',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 2,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'View/Edit Rights',
                'url' => 'edit-roles-users/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Add User',
                'url' => 'add-users',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Users List',
                'url' => 'list-users',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 1,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'List Roles',
                'url' => 'list-roles',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 3,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Edit Roles',
                'url' => 'edit-roles',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Delete Roles',
                'url' => 'delete-roles',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Edit User',
                'url' => 'edit-users',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Edit Roles User',
                'url' => 'edit-roles-users',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Delete User',
                'url' => 'delete-users',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 2,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'Edit Leave Record',
                'url' => 'edit-leave/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'Delete Leave Record',
                'url' => 'delete-leave/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'Edit Employees',
                'url' => 'edit-employees/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'name' => 'View Employee Document',
                'url' => 'view-employees-document/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'name' => 'Delete Employee',
                'url' => 'delete-employee/',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'Add Employee',
                'url' => 'add-employees',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 100,
                'name' => 'Reports',
                'url' => '#',
                'icon_type' => 0,
                'icon_image' => 'fa-copy',
                'is_parent' => 0,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 1,
                'is_listable' => 1,
                'is_dropdown' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 31,
                'name' => 'Employees Report',
                'url' => 'report-employees',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 51,
                'sort_order' => 1,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 32,
                'name' => 'Users Report',
                'url' => 'report-users',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 100,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 33,
                'name' => 'Attendance',
                'url' => 'list-attendance',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 5,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 35,
                'name' => 'Edit Attendance',
                'url' => 'edit-attendance',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'name' => 'Add Attendance',
                'url' => 'add-attendance',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 36,
                'name' => 'Delete Attendance',
                'url' => 'delete-attendance',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 37,
                'name' => 'Payroll',
                'url' => 'list-payroll',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 6,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 38,
                'name' => 'Generate Payslip',
                'url' => 'generate-payslip',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'name' => 'View Payroll',
                'url' => 'view-payroll',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'name' => 'Edit Salary',
                'url' => 'edit-salary',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'name' => 'Delete Salary',
                'url' => 'delete-salary',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'name' => 'Leave Report',
                'url' => 'report-leave',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 51,
                'sort_order' => 2,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'name' => 'Payroll Report',
                'url' => 'report-payroll',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 51,
                'sort_order' => 6,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'name' => 'Payslip Settings',
                'url' => 'setting-payslip',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],

            [
                'id' => 46,
                'name' => 'Add Employee Salary',
                'url' => 'add-employee-salary',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],

            [
                'id' => 47,
                'name' => 'List Salary',
                'url' => 'list-salary',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],

            [
                'id' => 48,
                'name' => 'Manual Payslip',
                'url' => 'manual-payslip',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],

            [
                'id' => 49,
                'name' => 'Delete Payroll',
                'url' => 'delete-payroll',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 50,
                'name' => 'Employee Profile',
                'url' => 'employee-profile',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 15,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 0,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 51,
                'name' => 'HR Reports',
                'url' => '#',
                'icon_type' => 0,
                'icon_image' => 'fa-copy',
                'is_parent' => 0,
                'sort_order' => 0,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 52,
                'name' => 'Salary Report',
                'url' => 'report-salary',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 51,
                'sort_order' => 7,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 53,
                'name' => 'Timesheet Report',
                'url' => 'report-timesheet',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 51,
                'sort_order' => 3,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 54,
                'name' => 'Attendance Summary Report',
                'url' => 'report-attendance',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 51,
                'sort_order' => 4,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 55,
                'name' => 'Monthly Attendance Report',
                'url' => 'report-monthly-attendance',
                'icon_type' => null,
                'icon_image' => null,
                'is_parent' => 51,
                'sort_order' => 5,
                'is_enabled' => 1,
                'is_new_tab' => 0,
                'is_listable' => 1,
                'is_dropdown' => 0,
                'created_at' => null,
                'updated_at' => null,
            ]

        ]);
    }
}
